resilience4j:
  circuitbreaker:
    instances:
      review-service:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 4
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        record-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException

  ratelimiter:
    instances:
      calculator-service:
        limit-refresh-period: 20s
        limit-for-period: 5
        timeout-duration: 5s
      review-service:
        limit-refresh-period: 20s
        limit-for-period: 3
        timeout-duration: 0s