spring.application.name=webflux-patterns

sec01.product.service=http://localhost:7070/sec01/product/
sec01.promotion.service=http://localhost:7070/sec01/promotion/
sec01.review.service=http://localhost:7070/sec01/review/